### ISSUE TITLE
Can't launch app on Android Emulator with API 28

### ISSUE THREAD

**Issue by vovaklh20012** [espresso3389/flutter_pdf_render#58]
I get the next error when trying to build my project
![image](https://user-images.githubusercontent.com/85889928/141452231-f3c548c8-1601-4a5a-a558-ac50a9fb3ed9.png)

**Comment by espresso3389** [comment]
The error seems from VSCode not from Flutter toolchain.
Please try starting `flutter run` or `flutter build` from command line not from VSCode.

And,... I'm afraid that the actual cause seems your home directory name; in your screenshot, your username is garbeled.
Please try to build the project outside your home directory, e.g. `C:\work`.

**Comment by MichaelDark** [comment]
@espresso3389 We investigated this issue. This was due to Cyrillic symbols in the path. Moving pub cache via environment variable PUB_CACHE fixed the issue
